# Generated by Django 3.1 on 2023-06-19 20:18

import chargily_epay_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('invoice_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('discount', models.FloatField(blank=True, default=0, max_length=2)),
                ('mode', models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25)),
                ('status', models.CharField(choices=[('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('progress', 'IN PROGRESS'), ('paid', 'PAID')], default='progress', max_length=25)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(chargily_epay_django.models.FakePaymentMixin, models.Model),
        ),
    ]
