# Generated by Django 3.1 on 2023-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='mode',
            field=models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('expired', 'EXPIRED'), ('failed', 'FAILED'), ('paid', 'PAID')], default='progress', max_length=25),
        ),
    ]
