# Generated by Django 3.1 on 2023-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0002_auto_20230623_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('progress', 'IN PROGRESS'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('paid', 'PAID')], default='progress', max_length=25),
        ),
    ]
