# Generated by Django 3.1 on 2023-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epay', '0003_auto_20230623_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('paid', 'PAID'), ('expired', 'EXPIRED'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED')], default='progress', max_length=25),
        ),
    ]
