# Generated by Django 3.1 on 2023-06-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ML', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttemplate'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttemplate'),
        ),
    ]
