from django.db import models
from partners.models import Company

class Parametres(models.Model):
    id = models.BigAutoField(primary_key=True)
    tva = models.FloatField(null=True)
    logo = models.BinaryField(null=True)
    company_name = models.CharField(max_length=255)
class ProductCategory(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    company_id = models.IntegerField(null=True)
class ProductUOM(models.Model):
    id = models.BigAutoField(primary_key=True)
    create_uid = models.IntegerField(null=True)
    create_date = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=255, null=True)
    rounding = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    write_uid = models.IntegerField(null=True)
    active = models.BooleanField(null=True)
    write_date = models.DateTimeField(null=True, blank=True)
    factor = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    uom_type = models.CharField(max_length=255, null=True)
class ProductTemplate(models.Model):
    id = models.BigAutoField(primary_key=True,  db_index=True)
    warranty = models.FloatField(null=True)
    uos_id = models.IntegerField(null=True)
    list_price = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    weight = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    color = models.IntegerField(null=True)
    image = models.BinaryField(null=True)
    write_uid = models.IntegerField(null=True)
    mes_type = models.CharField(max_length=255, null=True)
    uom_id = models.ForeignKey(ProductUOM, on_delete=models.CASCADE, null=True, default=22)
    description_purchase = models.TextField(null=True)
    create_date = models.DateTimeField(null=True)
    uos_coeff = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    create_uid = models.IntegerField(null=True)
    sale_ok = models.BooleanField(null=True)
    categ_id = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=True)
    product_manager = models.IntegerField(null=True)
    message_last_post = models.DateTimeField(null=True)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, default=8)
    state = models.CharField(max_length=255, null=True)
    uom_po_id = models.IntegerField(null=True)
    description_sale = models.TextField(null=True)
    description = models.TextField(null=True)
    weight_net = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    volume = models.FloatField(null=True)
    write_date = models.DateTimeField(null=True)
    active = models.BooleanField(null=True)
    rental = models.BooleanField(null=True)
    image_medium = models.BinaryField(null=True)
    name = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    image_small = models.BinaryField(null=True)
    sale_delay = models.FloatField(null=True)
    is_kit = models.BooleanField(null=True)
    is_system = models.BooleanField(null=True)
    can_be_sold_without_kit = models.BooleanField(null=True)
    accept_supplements = models.BooleanField(null=True)
    min_price_variant = models.FloatField(null=True)
    template_code = models.CharField(max_length=64, null=True)
    accept_variant = models.BooleanField(null=True)
    loc_rack = models.CharField(max_length=16, null=True)
    track_all = models.BooleanField(null=True)
    loc_row = models.CharField(max_length=16, null=True)
    loc_case = models.CharField(max_length=16, null=True)
    track_incoming = models.BooleanField(null=True)
    track_outgoing = models.BooleanField(null=True)
    stock_method = models.CharField(max_length=255, null=True)
    purchase_ok = models.BooleanField(null=True)
    use_time = models.IntegerField(null=True)
    life_time = models.IntegerField(null=True)
    removal_time = models.IntegerField(null=True)
    alert_time = models.IntegerField(null=True)
    track_production = models.BooleanField(null=True)
    produce_delay = models.FloatField(null=True)
    use_serial_number = models.BooleanField(null=True)
    manage_by_surface_or_volume = models.CharField(max_length=255, null=True)
    prefix_38_imp = models.CharField(max_length=1, null=True)
    prefix_category = models.CharField(max_length=255, null=True)
    prefix_3 = models.CharField(max_length=4, null=True)
    prefix_38_inter = models.CharField(max_length=1, null=True)
    prefix_6_expense = models.CharField(max_length=4, null=True)
    prefix_ff = models.CharField(max_length=2, null=True)
    prefix_38 = models.CharField(max_length=3, null=True)
    prefix_gf = models.CharField(max_length=2, null=True)
    prefix_6_variation = models.CharField(max_length=4, null=True)
    prefix_7_income = models.CharField(max_length=3, null=True)
    prefix_38_local = models.CharField(max_length=1, null=True)
    prefix_al= models.CharField(max_length=2, null=True)
    prefix_7_production= models.CharField(max_length=3, null=True)
    gmao_service= models.BooleanField(null=True)
class ProductPackaging(models.Model):
    id = models.AutoField(primary_key=True)
    create_uid = models.IntegerField(null=True)
    rows = models.IntegerField(null=True)
    create_date = models.DateTimeField(null=True)
    name = models.TextField(null=True)
    weight = models.FloatField(null=True)
    ean = models.CharField(max_length=14, null=True)
    ul_qty = models.IntegerField(null=True)
    sequence = models.IntegerField(null=True)
    qty = models.FloatField(null=True)
    product_tmpl_id = models.ForeignKey(ProductTemplate, on_delete=models.CASCADE, null=True, default=1)
    ul = models.IntegerField(null=True)
    code = models.CharField(max_length=255, null=True)
    write_date = models.DateTimeField(null=True)
    ul_container = models.IntegerField(null=True)
    write_uid = models.IntegerField(null=True)
    ul_name = models.CharField(max_length=255, null=True)
class ProductFinal(models.Model):
    tmpl_id = models.IntegerField(null=True)
    warranty = models.FloatField(null=True)
    uos_id = models.IntegerField(null=True)
    list_price = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    weight = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    color = models.IntegerField(null=True)
    image = models.BinaryField(null=True)
    write_uid = models.IntegerField(null=True)
    mes_type = models.CharField(max_length=255, null=True)
    uom_id = models.ForeignKey(ProductUOM, on_delete=models.CASCADE, null=True, default=22)
    description_purchase = models.TextField(null=True)
    create_date = models.DateTimeField(null=True)
    uos_coeff = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    create_uid = models.IntegerField(null=True)
    sale_ok = models.BooleanField(null=True)
    categ_id = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=True)
    product_manager = models.IntegerField(null=True)
    message_last_post = models.DateTimeField(null=True)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, default=8)
    state = models.CharField(max_length=255, null=True)
    uom_po_id = models.IntegerField(null=True)
    description_sale = models.TextField(null=True)
    description = models.TextField(null=True)
    weight_net = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    volume = models.FloatField(null=True)
    write_date = models.DateTimeField(null=True)
    active = models.BooleanField(null=True)
    rental = models.BooleanField(null=True)
    image_medium = models.BinaryField(null=True)
    name = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    image_small = models.BinaryField(null=True)
    sale_delay = models.FloatField(null=True)
    is_kit = models.BooleanField(null=True)
    is_system = models.BooleanField(null=True)
    can_be_sold_without_kit = models.BooleanField(null=True)
    accept_supplements = models.BooleanField(null=True)
    min_price_variant = models.FloatField(null=True)
    template_code = models.CharField(max_length=64, null=True)
    accept_variant = models.BooleanField(null=True)
    loc_rack = models.CharField(max_length=16, null=True)
    track_all = models.BooleanField(null=True)
    loc_row = models.CharField(max_length=16, null=True)
    loc_case = models.CharField(max_length=16, null=True)
    track_incoming = models.BooleanField(null=True)
    track_outgoing = models.BooleanField(null=True)
    stock_method = models.CharField(max_length=255, null=True)
    purchase_ok = models.BooleanField(null=True)
    use_time = models.IntegerField(null=True)
    life_time = models.IntegerField(null=True)
    removal_time = models.IntegerField(null=True)
    alert_time = models.IntegerField(null=True)
    track_production = models.BooleanField(null=True)
    produce_delay = models.FloatField(null=True)
    use_serial_number = models.BooleanField(null=True)
    manage_by_surface_or_volume = models.CharField(max_length=255, null=True)
    prefix_38_imp = models.CharField(max_length=1, null=True)
    prefix_category = models.CharField(max_length=255, null=True)
    prefix_3 = models.CharField(max_length=4, null=True)
    prefix_38_inter = models.CharField(max_length=1, null=True)
    prefix_6_expense = models.CharField(max_length=4, null=True)
    prefix_ff = models.CharField(max_length=2, null=True)
    prefix_38 = models.CharField(max_length=3, null=True)
    prefix_gf = models.CharField(max_length=2, null=True)
    prefix_6_variation = models.CharField(max_length=4, null=True)
    prefix_7_income = models.CharField(max_length=3, null=True)
    prefix_38_local = models.CharField(max_length=1, null=True)
    prefix_al= models.CharField(max_length=2, null=True)
    prefix_7_production= models.CharField(max_length=3, null=True)
    gmao_service= models.BooleanField(null=True)
    product_product_id =models.IntegerField(null=True)
    attribute = models.CharField(max_length=255, null=True)
    attribute_value = models.CharField(max_length=255, null=True)