# Generated by Django 3.1 on 2023-06-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panier', '0001_initial'),
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='order_partner_id',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='product_id',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.productproduct'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='product_packaging',
            field=models.ForeignKey(default=278, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productpackaging'),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='product_uom',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productuom'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='partner_id',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partners'),
        ),
    ]
