# Generated by Django 3.1 on 2023-06-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panier', '0002_auto_20230619_2118'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='user_partner',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_partner_sale_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_uid_sale_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productproduct',
            name='product_tmpl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttemplate'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.productproduct'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.productproduct'),
        ),
    ]
